Repository DeveloperAcademy-POSTECH/MC2PocketCaddy, pull requests merged in 2022-06, with the labels that each got.

#6 [#3] Build DescriptionView and test merge
  PocketCaddy/PocketCaddy/Scene/DescriptionView.swift
Labels: enhancement

#9 Tutorial
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/LifeCycle/PocketCaddyApp.swift
  PocketCaddy/PocketCaddy/Tutorial/SampleData.json
  PocketCaddy/PocketCaddy/Tutorial/SampleModel.swift
  PocketCaddy/PocketCaddy/Tutorial/SampleReader.swift
  PocketCaddy/PocketCaddy/Tutorial/SampleView.swift
Labels: help wanted

#16 Json parsing 클래스 작업
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/JsonData/JsonDataManager.swift
  PocketCaddy/PocketCaddy/LifeCycle/PocketCaddyApp.swift
  PocketCaddy/PocketCaddy/Model/Club.json
  PocketCaddy/PocketCaddy/Model/ClubModel.swift
Labels: enhancement

#17 [#15] add searchLogic 추가 , jsonDataManager 수정
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/JsonData/JsonDataManager.swift
  PocketCaddy/PocketCaddy/Model/SearchLogic.swift
Labels: enhancement

#18 Json parsing 오류 수정
  PocketCaddy/PocketCaddy/JsonData/JsonDataManager.swift
  PocketCaddy/PocketCaddy/Model/Club.json
  PocketCaddy/PocketCaddy/Scene/MapView.swift
Labels: bug

#24 Bug fix map view
  PocketCaddy/PocketCaddy/Scene/Map/ImageView.swift
  PocketCaddy/PocketCaddy/Scene/Map/MapView.swift
  PocketCaddy/PocketCaddy/Scene/Map/TextImageView.swift
Labels: bug

#32 DescriptionView UI 작업완료
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Category.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Category.imageset/􀉟 Category.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/CutBackground.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/CutBackground.imageset/CutBackground.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Distance.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Distance.imageset/􀄭 Distance.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Location.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Location.imageset/􀋒 Location.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/RoundDriverButton.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/RoundDriverButton.imageset/RoundDriverButton.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/TestClub.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/TestClub.imageset/TestClub.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/GreenBackground.colorset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/GreenForeground.colorset/Contents.json
  PocketCaddy/PocketCaddy/Util/ColorExtension.swift
Labels: enhancement

#41 CHORE: README update
  README.md
Labels: Ready to merge

#44 Search view
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
  PocketCaddy/PocketCaddy/Scene/ClubCardView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: documentation, enhancement

#45 Description view 작업완료
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Category.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Distance.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/Location.imageset/Contents.json
Labels: enhancement

#48 [#30] LaunchView 깃발 크기, 위치 및 배경 그라디언트 변경
  PocketCaddy/PocketCaddy/MainView/LaunchScene.swift
  PocketCaddy/PocketCaddy/MainView/LaunchView.swift
Labels: documentation

#49 [#34] Update searchClub Func
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
Labels: documentation

#51 Refactoring
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/MainView/HomeView.swift
  PocketCaddy/PocketCaddy/MainView/LaunchScene.swift
  PocketCaddy/PocketCaddy/MainView/LaunchView.swift
  PocketCaddy/PocketCaddy/MainView/UIImage.swift
  PocketCaddy/PocketCaddy/Scene/ClubCardView.swift
  PocketCaddy/PocketCaddy/Scene/CustomBackButton.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/Map/MapView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
  PocketCaddy/PocketCaddy/Util/HomeViewTip.swift
  PocketCaddy/PocketCaddy/Util/LazyVGridSetting.swift
Labels: refactoring

#55 [#31] SelectionView에 사용할 색상 추가
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/ColorSet/PrimaryGray.colorset/Contents.json
Labels: enhancement

#58 [#31] PrimaryGray 색 수정 및 extension 추가
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/ColorSet/PrimaryGray.colorset/Contents.json
  PocketCaddy/PocketCaddy/Util/ColorExtension.swift
Labels: documentation

#59 Description view logic 연결 완료
  PocketCaddy/PocketCaddy/MainView/HomeView.swift
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: enhancement

#62 Search view 업데이트
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: bug

#63 Refactor: SelectionView bake button location fixed
  PocketCaddy/PocketCaddy/MainView/HomeView.swift
  PocketCaddy/PocketCaddy/Scene/CustomBackButton.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: refactoring

#64 [#31] 클럽 category 및 location 대문자로 변경 외 2개
  PocketCaddy/PocketCaddy/Model/Club/Club.json
  PocketCaddy/PocketCaddy/Model/Club/ClubModel.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/AW.imageset/Approach Wedge.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/AW.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/LW.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/LW.imageset/Lob Wedge.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/PW.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/PW.imageset/Pitching Wedge.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/SW.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Golf Clubs/SW.imageset/Sand Wedge.png
Labels: documentation

#65 [#25] SelectionView disabled 버튼 색 바꿨습니다.
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: enhancement

#67 [#31] FEAT: SelectionView Distance section animation
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: enhancement

#70 [#69] HOTFIX: Handled various errors
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: bug

#71 Description view UI 수정 작업
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
Labels: Fix UI

#73 FEAT: Speech bubble, home view ui
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/MainView/Home/HomeView.swift
  PocketCaddy/PocketCaddy/MainView/Home/SpeechBubble.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: enhancement

#75 [#50] HomeView UI 수정했습니다.
  PocketCaddy/PocketCaddy/MainView/Home/HomeView.swift
  PocketCaddy/PocketCaddy/MainView/LaunchView.swift
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn-2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/secondbuttonx2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/secondbuttonx3.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn-2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/firstbuttonx2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/firstbuttonx3.png
Labels: refactoring

#76 [#50] DescriptionView 관련 파일 정리
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionPageView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
Labels: refactoring

#78 [#50] SelectionView에서 발생하는 오류 수정
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/SelectionButton.swift
Labels: refactoring

#79 [#50] iPages 라이브러리 종속성 삭제
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: refactoring

#81 FEAT: Lightmode fixed
  PocketCaddy/PocketCaddy/LifeCycle/PocketCaddyApp.swift
Labels: enhancement

#82 [#31] HomeView 버튼 png로 변경
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn-2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn@1x-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn@2x.png-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/AllClubBtn@3x.png-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/AllClubBtn.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn-2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn@1x-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn@2x-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/LocationAndDistanceBtn.imageset/LocationAndDistanceBtn@3x-1.png
Labels: documentation

#83 [#31] 앱 아이콘 png 변경
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/1024.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/120-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/120.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/152.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/167.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/180.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/20.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/29.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/40-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/40-2.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/40.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/58-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/58.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/60.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/76.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/80-1.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/80.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AppIcon.appiconset/87.png
Labels: documentation

#84 [#50] 뒤로가는 버튼 눌리는 효과 추가
  PocketCaddy/PocketCaddy/MainView/Home/HomeView.swift
  PocketCaddy/PocketCaddy/Scene/CustomBackButton.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: enhancement

#85 팀 세팅 완료
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/AccentColor.colorset/Contents.json
Labels: setting

#89 [#50] view backbutton 누르면 transition 효과 사라지는 오류 수정
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: refactoring

#90 FEAT: Add button from Description view to map view, animation error h…
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionPageView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Description/SelectionView.swift
  PocketCaddy/PocketCaddy/Scene/SearchView.swift
Labels: enhancement

#92 Add map view to selection view
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/Scene/Description/ClubCardView.swift
  PocketCaddy/PocketCaddy/Scene/Home/HomeSelection.swift
  PocketCaddy/PocketCaddy/Scene/Home/HomeView.swift
  PocketCaddy/PocketCaddy/Scene/Home/SpeechBubble.swift
  PocketCaddy/PocketCaddy/Scene/Launch/ActionList.sks
  PocketCaddy/PocketCaddy/Scene/Launch/Base.lproj/action.sks
  PocketCaddy/PocketCaddy/Scene/Launch/GifImage.swift
  PocketCaddy/PocketCaddy/Scene/Launch/LaunchScene.swift
  PocketCaddy/PocketCaddy/Scene/Launch/LaunchView.swift
  PocketCaddy/PocketCaddy/Scene/Launch/Timer.swift
  PocketCaddy/PocketCaddy/Scene/Launch/UIImage.swift
  PocketCaddy/PocketCaddy/Scene/Launch/flag.gif
  PocketCaddy/PocketCaddy/Scene/Map/MapView.swift
  PocketCaddy/PocketCaddy/Scene/Search/SearchView.swift
  PocketCaddy/PocketCaddy/Scene/Selection/SelectionButton.swift
  PocketCaddy/PocketCaddy/Scene/Selection/SelectionView.swift
  PocketCaddy/PocketCaddy/Tutorial/JSONReading/SampleData.json
  PocketCaddy/PocketCaddy/Tutorial/JSONReading/SampleModel.swift
  PocketCaddy/PocketCaddy/Tutorial/JSONReading/SampleReader.swift
  PocketCaddy/PocketCaddy/Tutorial/JSONReading/SampleView.swift
  PocketCaddy/PocketCaddy/Tutorial/SearchLogic/DataManager/SampleClubDataManager.swift
  PocketCaddy/PocketCaddy/Tutorial/SearchLogic/SampleDescriptionView.swift
  PocketCaddy/PocketCaddy/Tutorial/SearchLogic/SampleSelectionComponents.swift
  PocketCaddy/PocketCaddy/Tutorial/SearchLogic/SampleSelectionView.swift
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/CutBackground.imageset/CutBackground.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/TestClub.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/DescriptionView/TestClub.imageset/TestClub.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/CircleQuestionmark.imageset/Contents.json
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/CircleQuestionmark.imageset/circleQuestionmark.png
  PocketCaddy/PocketCaddy/Util/Assets.xcassets/Home/CircleQuestionmark.imageset/circleQuestionmark2.png
Labels: enhancement

#96 Refactoring
  PocketCaddy/PocketCaddy/Scene/CustomBackButton.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionPageView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Search/SearchView.swift
  PocketCaddy/PocketCaddy/Scene/Selection/SelectionView.swift
Labels: bug, enhancement

#98 Search view update
  PocketCaddy/PocketCaddy.xcodeproj/project.pbxproj
  PocketCaddy/PocketCaddy/Model/Club/ClubDataManager.swift
  PocketCaddy/PocketCaddy/Scene/CustomBackButton.swift
  PocketCaddy/PocketCaddy/Scene/Description/ClubCardView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionPageView.swift
  PocketCaddy/PocketCaddy/Scene/Description/DescriptionSingleView.swift
  PocketCaddy/PocketCaddy/Scene/Search/ClubCardView.swift
  PocketCaddy/PocketCaddy/Scene/Search/SearchView.swift
  PocketCaddy/PocketCaddy/Scene/Selection/SelectionView.swift
Labels: bug, enhancement
